### PR TITLE
Display the type at the cursor with alt+a

### PR DESCRIPTION
**Pull request by TheSpyder**
This wasn't difficult to achieve, the only real change to make the existing code work with `ocp-index type` was that instead of cutting the line off at the cursor, we extend it to the end of the current word using sublime's `view.word()` function.

After that, everything else was refactoring:
- Type checking requires specific build detail that completion just searches for, so I had to make a way to provide the `--build` parameter before it worked in my project.
- A single class can't be used as both a Sublime event listener and command listener, and I didn't want to make everything top-level, so I extracted the logic to a new class.
- The old code was rearranged into query extraction, ocp-index execution, and completion-specific logic. This lets `query_type` be a very simple method. There are probably better ways to achieve this, I'm not a complete python guru :)

I've done command line experiments with `--context` to solve the limitation I mention in the readme, but extracting that information from sublime could be tricky. I want to get your feedback on the bulk of the change before I spend any more time on it :)

### CODE REVIEW

**Comment by whitequark** [comment]
by the way I've tried out your branch and even with ocp-index's limited understanding of code it's quite nice to use.

**Comment by TheSpyder** [comment]
Thanks! A quick search of the API reveals a `view.rowcol(point)` method in sublime that will make supplying the correct information to `--context` easy. I'll see if I can wrangle that in as well as the settings fix - I've already confirmed at the command line that using it makes ocp-index work inside `let open <module> in` statements which is pretty fancy.

**Comment by TheSpyder** [comment]
OK, I think everything is solved. I even switched to `-F` for the current module instead of `-O`, which loads the elements that would be hidden by the interface.

It's fantastic in my testing :)

**Comment by whitequark** [comment]
thanks!

**Comment by TheSpyder** [comment]
So fast! I was about to add an extra fix for running type inspection at the start of variables that include underscores. Will that have to be a new pull request now? :)

**Comment by whitequark** [comment]
hm, I think so!

**Pull request merged**
