### PR TITLE
Fix autocomplete with OPAM modules

### PR DESCRIPTION
**Pull request by TheSpyder**
While the documentation for `ocp-index -I` doesn't make it particularly clear, the default behaviour (locate the OPAM folder and search OPAM packages for autocompletion) is disabled when you use it. I figured you had a reason for making use of it, so I've left that as the default and added an option to disable searching local libraries.

A couple of bonus changes:
- I added a `#` to the line regex to include object method calls in autocompletion.
- ocamlbuild appears to support the `bin_annot` tag out of the box now, using your fix actually passes it twice to ocamlc. I have no idea if this is new in 4.01 but I assume it is. Updated the readme.

### CODE REVIEW

**Comment by whitequark** [comment]
Thanks!

**Comment by whitequark** [comment]
The problem with `ocp-index` is that it doesn't allow to _append_ `-I` paths instead of replacing and the OPAM autodetection code is hard to duplicate in sublime-ocp-index (I've looked into it.)

Patches and ideas are welcome.

**Comment by TheSpyder** [comment]
Cool. On a related note I think I've figured out how to display the type of the variable at the cursor similar to how https://github.com/erpheus/Sublime-OcamlUtils does it but using ocp-index. Would you be interested in a pull request for that?

**Comment by TheSpyder** [comment]
Yeah I had a look at appending search paths and ran screaming. I'm not brave enough to start playing with the ocp-index code yet :)

**Comment by whitequark** [comment]
of course! this would be a very nice addition.

**Comment by AltGr** [comment]
Sorry, that would be the cmdliner part :)
I agree the command-line options of ocp-index may not be perfect at the moment, don't hesitate to ask for improvements rather than attempting workarounds :)

I guess a simple option `--[no-]stdlib` to toggle auto-location of the stdlib using `opam config var lib`/`ocamlc -where` would do the trick ? If we want to stay backwards-compatible that would be on by default unless `-I` is specified.

**Comment by TheSpyder** [comment]
Normally I would start with improving ocp-index but I'm still fairly new at OCaml and I want to get a bit more comfortable with the language before tackling the bigger codebases. I was aiming to dig into it and maybe submit a pull request next week :)

An extra option to enable stdlib when `-I` is used would be awesome, that way it's backwards compatible for people using this plugin who haven't upgraded ocp-index.

**Comment by whitequark** [comment]
@AltGr yes, `--[no-]stdlib` would be awesome and it would solve all issues we have.

**Comment by AltGr** [comment]
https://github.com/OCamlPro/ocp-index/commit/1fe9643b4b19aa8414381c133b8fe3373d735ac5 should provide just what you need :)

**Comment by TheSpyder** [comment]
Cool. So you made it `--opamlib` instead?

**Pull request merged**
